### ISSUE TITLE
DISTINCT Causes error in MSSQL

### ISSUE THREAD

**Issue by seanford** [sebtools/DataMgr#3]
When using DISTINCT with maxrows (or TOP XX), the DISTINCT clause must appear before TOP.  This can be fixed by re-ordering the following if/then statements (approx line 1574), placing the DISTINCT one first.

```
<cfif StructKeyExists(arguments,"distinct") AND arguments.distinct IS true>
<cfset ArrayAppend(sqlarray,"DISTINCT")>
</cfif>
<cfif arguments.maxrows GT 0>
<cfset ArrayAppend(sqlarray,getMaxRowsPrefix(arguments.maxrows,arguments.offset))>
</cfif>
```

**Comment by sebtools** [comment]
Sorry for the delay. I added this now. Thanks!
